# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Create a Ubuntu remote environment/Runner where the workflow can run and build the Image.
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Login to the Remote Machine via SSH using the pre-written workflow by Official Github Actions
    # i.e Checkout.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setting up AWS CLI/SDK on Remote Host and Configuring AWS Login Credentials and Assuming
      # Roles using the pre-written workflow by Official AWS Teams
      # i.e Configure AWS Credentials.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Building the Docker Image by copying using the Code in our Repository (Dockerfile),
      # Tagging the Image with a version, and Pushing it to an Elastic Container Registry.
      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: 1.0
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
